### PR TITLE
Added check/uncheck all checkbox on List header

### PR DESCRIPTION
**Pull request by piyushpaliwal**

### CODE REVIEW

**Comment by piyushpaliwal** [comment]
@DigitalFlow let me know if this works.

**Comment by DigitalFlow** [comment]
Hi @piyushpaliwal,

Thanks for your work 👍 
I'll take a look and give you a note. Should happen rather fast.

Kind Regards,
Florian

**Comment by piyushpaliwal** [comment]
> 
> 
> Hi @piyushpaliwal,
> 
> Thanks for your work 👍
> I'll take a look and give you a note. Should happen rather fast.
> 
> Kind Regards,
> Florian

@DigitalFlow Florian, you got a chance to look into this?

**Comment by DigitalFlow** [comment]
Hey @piyushpaliwal,

Just finished testing, works as intended.
Awesome, thanks a lot 👍 

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Published as v1.2.0

**Pull request merged**
